improve aggregate performance by verifying the aggregate signature first
ZcashFoundation/frost pull request #207
Opened 2022-12-16 19:46 UTC by conradoplg

Implements https://github.com/cfrg/draft-irtf-cfrg-frost/pull/360

2023-01-11 00:41 UTC, upbqdn requested changes
PR looks great. I noticed an outdated comment that I think we should change before merging this PR, so I'm requesting changes.

See https://github.com/ZcashFoundation/frost/blob/78e67d175b71deae26dec6ab608918e1e55b0234/frost-core/src/frost.rs#L326-L327

2023-01-11 00:41 UTC, upbqdn commented on frost-core/src/frost.rs
> +    // If verification failed; verify each share to find the cheater.
The "only if" construct might be handy here:
```suggestion
    // Only if the verification of the aggregate signature failed; verify each share to find the cheater.
```

2023-01-11 03:11 UTC, dconnolly commented on frost-core/src/frost.rs
> +    // This approach is more efficient since we don't need to verificate all shares
```suggestion
    // This approach is more efficient since we don't need to verify all shares
```

2023-01-11 03:16 UTC, dconnolly submitted a review, later dismissed
🎉

2023-01-11 03:19 UTC, dconnolly approved these changes

2023-01-11 14:43 UTC, upbqdn reviewed
Looks great. However, I still think we should update this comment. https://github.com/ZcashFoundation/frost/blob/78e67d175b71deae26dec6ab608918e1e55b0234/frost-core/src/frost.rs#L326-L327

Unfortunately, GitHub won't let me make a suggestion.

2023-01-11 16:51 UTC, conradoplg commented
> Looks great. However, I still think we should update this comment.
> 
> https://github.com/ZcashFoundation/frost/blob/78e67d175b71deae26dec6ab608918e1e55b0234/frost-core/src/frost.rs#L326-L327
> 
> Unfortunately, GitHub won't let me make a suggestion.

Good catch, fixed it in a904af6, I also removed some outdated wording

2023-01-12 00:00 UTC, upbqdn approved these changes

2023-01-12 00:16 UTC, merged