frost-rerandomized: add aggregate optimization
ZcashFoundation/frost pull request #214
Opened 2023-01-12 23:38 UTC by conradoplg

This is basically the same as #207 but for `frost-rerandomized`.

2023-01-25 23:01 UTC, upbqdn requested changes
Looks great, but let's update this comment as well. https://github.com/ZcashFoundation/frost/blob/328796e239caf96083f666a7cc4163eec7998d7a/frost-rerandomized/src/lib.rs#L71-L72

2023-02-03 21:34 UTC, dconnolly approved these changes

2023-02-03 21:40 UTC, dconnolly commented
> Looks great, but let's update this comment as well.
> 
> https://github.com/ZcashFoundation/frost/blob/328796e239caf96083f666a7cc4163eec7998d7a/frost-rerandomized/src/lib.rs#L71-L72

Done in 09ffa9e102285af015c1fdf2c82119a1f185664e

2023-02-03 21:40 UTC, dconnolly submitted a review, later dismissed

2023-02-05 23:41 UTC, upbqdn submitted a review, later dismissed

2023-02-06 23:36 UTC, dconnolly approved these changes

2023-02-06 23:49 UTC, merged