check number of commitments in sign()
ZcashFoundation/frost pull request #480
Opened 2023-08-17 15:43 UTC by conradoplg

Closes https://github.com/ZcashFoundation/frost/issues/455

Not fully sure if it's worth checking this (it's not required, the signature generation would fail anyway), but it works as a second layer of validation and it seems useful for users to be able to know what is the min_signers value by getting it from the KeyPackage. Let me know what you think.

This also adds a test for trying to sign with less than min_signers share (even bypassing this new min_signers value check) which is useful in itself and makes sure we're not interpreting thresholds wrong.

2023-09-04 16:28 UTC, conradoplg commented
Solved conflicts

2023-09-04 17:21 UTC, natalieesk commented on frost-core/src/tests/ciphersuite_generic.rs
> +    // Check if it fails with not enough signers. To bypass the min_signers value
I find this comment a bit confusing

2023-09-04 17:21 UTC, natalieesk commented on frost-core/src/tests/ciphersuite_generic.rs
> +    // check, also reduce the min_signers in KeyPackages.
I find this comment a bit confusing

2023-09-04 17:22 UTC, natalieesk requested changes
Looks good. Just one thing about making a comment clearer.

2023-09-04 18:10 UTC, conradoplg commented on frost-core/src/tests/ciphersuite_generic.rs
> +    // check, also reduce the min_signers in KeyPackages.
I expanded it in fa7f652

2023-09-05 09:49 UTC, natalieesk approved these changes

2023-09-05 09:51 UTC, natalieesk submitted a review, later dismissed

2023-09-06 09:48 UTC, merged