frost-core: expose SigningKey::to/from_scalar()
ZcashFoundation/frost pull request #601
Opened 2024-01-25 20:42 UTC by conradoplg

Closes #497

2024-01-31 14:11 UTC, natalieesk requested changes
Just a typo

2024-01-31 14:11 UTC, natalieesk commented on frost-core/CHANGELOG.md
> +* Exposed the `SignignKey::from_scalar()` and `to_scalar()` methods. This
typo `SigningKey::from_scalar()`

2024-01-31 21:01 UTC, conradoplg commented on frost-core/CHANGELOG.md
> +* Exposed the `SignignKey::from_scalar()` and `to_scalar()` methods. This
Oops, thanks!

```suggestion
* Exposed the `SigningKey::from_scalar()` and `to_scalar()` methods. This
```

2024-01-31 21:02 UTC, conradoplg commented on frost-core/CHANGELOG.md
> +* Exposed the `SignignKey::from_scalar()` and `to_scalar()` methods. This
Done in 6ba38c3

2024-02-01 13:06 UTC, natalieesk approved these changes
Great

2024-02-01 13:10 UTC, merged